version: '3.5'

services:
  webapp:
    image: bodarev2001/webapp:latest
    #build: testApp
    container_name: webapp
    restart: always
    ports:
      - "5050:80"
    depends_on: 
      - db
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    volumes:
        - /home/app/src/

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    hostname: sql1
    env_file:
      - .env
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${SQL_PASS}
    ports:
      - "1433:1433"
    volumes:
      - /home/app/db/
  db-management:
    image: sqlpad/sqlpad
    container_name: sqlpad
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      SQLPAD_ADMIN: ${SQLPAD_LOGIN}
      SQLPAD_ADMIN_PASSWORD: ${SQLPAD_PASS}
    volumes:
      - /home/app/sqlpad/
